// Central place resolving section.icon strings (stored as plain data in
// sections.config.ts) to actual lucide-react components.
import {
  Network,
  Plug,
  Database,
  Languages,
  BookOpen,
  Layers,
  GitBranch,
  MessagesSquare,
  ShieldCheck,
  Trophy,
  FolderGit2,
  GitMerge,
  History,
  GitPullRequest,
  Cloud,
  Server,
  Compass,
  KeyRound,
  ShieldAlert,
  HardDrive,
  Archive,
  Boxes,
  Blocks,
  LayoutGrid,
  Puzzle,
  Atom,
  PlugZap,
  ListChecks,
  Mic,
  type LucideIcon,
} from "lucide-react";

export const sectionIconMap: Record<string, LucideIcon> = {
  Network,
  Plug,
  Database,
  Languages,
  GitBranch,
  Cloud,
  Boxes,
};

export const moduleIconMap: Record<string, LucideIcon> = {
  fundamentals: BookOpen,
  "scalability-basics": Layers,
  "data-layer": Database,
  "distributed-systems": GitBranch,
  "communication-async": MessagesSquare,
  "reliability-ops": ShieldCheck,
  "case-studies": Trophy,
  foundations: FolderGit2,
  "branching-collaboration": GitMerge,
  "history-safety": History,
  "github-workflow": GitPullRequest,
  "core-services": Server,
  "architecture-strategy": Compass,
  "iam-fundamentals": KeyRound,
  "iam-advanced-ops": ShieldAlert,
  "s3-fundamentals": HardDrive,
  "s3-advanced-ops": Archive,
  "oop-foundations": Blocks,
  "four-pillars": LayoutGrid,
  "abstraction-tools": Puzzle,
  "advanced-oop": Atom,
  "oop-in-aspnet-core": PlugZap,
  "solid-patterns": ListChecks,
  "interview-delivery": Mic,
};
