// Central place resolving section.icon strings (stored as plain data in
// sections.config.ts) to actual lucide-react components.
import {
  Network,
  Plug,
  Database,
  Languages,
  BookOpen,
  Layers,
  GitBranch,
  MessagesSquare,
  ShieldCheck,
  Trophy,
  FolderGit2,
  GitMerge,
  History,
  GitPullRequest,
  Cloud,
  Server,
  Compass,
  KeyRound,
  ShieldAlert,
  HardDrive,
  Archive,
  Boxes,
  Blocks,
  LayoutGrid,
  Puzzle,
  Atom,
  PlugZap,
  ListChecks,
  Mic,
  Terminal,
  Binary,
  Braces,
  MemoryStick,
  ListTree,
  OctagonAlert,
  Zap,
  Filter,
  Cpu,
  Cog,
  Globe,
  Table2,
  Shapes,
  TestTube2,
  GraduationCap,
  Webhook,
  LayoutTemplate,
  GitCommit,
  Workflow,
  Rocket,
  Component,
  Code2,
  Sparkles,
  Share2,
  Waypoints,
  Route,
  ArrowRightLeft,
  FormInput,
  LayoutDashboard,
  Gauge,
  Hexagon,
  RefreshCw,
  Package,
  Wrench,
  Waves,
  Variable,
  Brackets,
  Parentheses,
  Split,
  type LucideIcon,
} from "lucide-react";

export const sectionIconMap: Record<string, LucideIcon> = {
  Network,
  Plug,
  Database,
  Languages,
  GitBranch,
  Cloud,
  Boxes,
  Terminal,
  GraduationCap,
  Workflow,
  Component,
  Hexagon,
  Braces,
};

export const moduleIconMap: Record<string, LucideIcon> = {
  fundamentals: BookOpen,
  "scalability-basics": Layers,
  "data-layer": Database,
  "distributed-systems": GitBranch,
  "communication-async": MessagesSquare,
  "reliability-ops": ShieldCheck,
  "case-studies": Trophy,
  foundations: FolderGit2,
  "branching-collaboration": GitMerge,
  "history-safety": History,
  "github-workflow": GitPullRequest,
  "core-services": Server,
  "architecture-strategy": Compass,
  "iam-fundamentals": KeyRound,
  "iam-advanced-ops": ShieldAlert,
  "s3-fundamentals": HardDrive,
  "s3-advanced-ops": Archive,
  "oop-foundations": Blocks,
  "four-pillars": LayoutGrid,
  "abstraction-tools": Puzzle,
  "advanced-oop": Atom,
  "oop-in-aspnet-core": PlugZap,
  "solid-patterns": ListChecks,
  "interview-delivery": Mic,
  "type-system": Binary,
  "csharp-language-fundamentals": Braces,
  "memory-gc": MemoryStick,
  "collections-generics": ListTree,
  "exception-handling-fundamentals": OctagonAlert,
  "delegates-events-lambda": Zap,
  "linq-fundamentals": Filter,
  "async-threading-parallel": Cpu,
  "dotnet-runtime-architecture": Cog,
  "aspnet-core-fundamentals": Globe,
  "data-access-adonet-efcore": Table2,
  "design-patterns-architecture": Shapes,
  "testing-and-others": TestTube2,
  "dotnet-web-api": Webhook,
  "angular-deep-dive": LayoutTemplate,
  "sql-deep-dive": Database,
  "aws-s3-deep-dive": HardDrive,
  "aws-lambda-deep-dive": Zap,
  "github-commands": GitCommit,
  "foundations-first-run": Rocket,
  "crud-in-memory": Boxes,
  "layered-architecture": Layers,
  "data-access-efcore": Database,
  "cross-cutting-concerns": Cog,
  security: ShieldCheck,
  "real-world-features": Puzzle,
  "quality-and-architecture": TestTube2,
  deployment: Cloud,
  "ng-foundations": Rocket,
  "components-templates-binding": Code2,
  "directives-pipes": Sparkles,
  "component-communication": Share2,
  "services-di-rxjs": Waypoints,
  "ng-routing": Route,
  "http-and-apis": ArrowRightLeft,
  "forms-and-crud": FormInput,
  "ng-real-world-features": LayoutDashboard,
  "quality-performance-deploy": Gauge,
  "js-for-node": Braces,
  "node-internals": Server,
  "event-loop": RefreshCw,
  "sync-async": ArrowRightLeft,
  "async-patterns": Waypoints,
  "modules-and-npm": Package,
  "builtin-modules": Wrench,
  "buffers-streams-files": Waves,
  "http-and-events": Globe,
  "concurrency-and-performance": Gauge,
  "variables-and-types": Variable,
  "objects-and-arrays": Brackets,
  functions: Parentheses,
  "control-flow": Split,
  "async-and-modules": RefreshCw,
};
